name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.19
        
    - uses: actions/checkout@v3

    - name: Build
      run: make build
      
    - name: Unit Test
      run: make test

    - name: Integration Test
      run: make integration-test
      
