name: ci

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.24
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Build
      run: CGO_ENABLED=0;go build -o /dev/null
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.24
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Integration Test
      run: tests/integration-tests.sh
        
    