name: ci

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.23
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Build
      run: make build
    